apiVersion: v1
kind: Service
metadata:
  name: proxy-load-balancer-service
spec:
  type: LoadBalancer
  selector:
    component: proxy
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  externalTrafficPolicy: Local