apiVersion: apps/v1
kind: Deployment
metadata:
  name: rick-and-morty-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      component: rick-and-morty
  template:
    metadata:
      labels:
        component: rick-and-morty
    spec:
      containers:
        - name: rick-and-morty-service
          image: grzesiekoladele/rick-and-morty:v2
          ports:
            - containerPort: 8000
          env:
            - name: REST-TEMPLATE_PROXY_HOST
              value: localhost
