proxy:
  docker:
    image:
      tag: v1
  replicas: 3

kanye:
  docker:
    image:
      tag: v1
  replicas: 3

report:
  docker:
    image:
      tage: v1
  replicas: 3
  database:
    docker:
      image:
        name: postgres
        tag: 14.1
    replicas: 1
    persistentVolumeClaim:
      volume:
        storage: 4Mi

rickAndMorty:
  docker:
    image:
      tag: v1
  replicas: 3