apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kanye.service.clusterIp.name }}
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.kanye.component }}
  ports:
    - port: {{ .Values.kanye.docker.container.port }}
      targetPort: {{ .Values.kanye.docker.container.port }}