apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxy.service.loadBalancer.name }}
spec:
  type: LoadBalancer
  selector:
    component: {{ .Values.proxy.component }}
  ports:
    - protocol: TCP
      port: {{  .Values.proxy.docker.container.port }}
      targetPort: {{  .Values.proxy.docker.container.port }}
  externalTrafficPolicy: Local