apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.report.service.clusterIp.name }}
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.report.component }}
  ports:
    - port: {{ .Values.report.docker.container.port }}
      targetPort: {{ .Values.report.docker.container.port }}