apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.report.database.persistentVolumeClaim.name}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.report.database.persistentVolumeClaim.volume.storage }}