apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.report.database.deployment.name }}
spec:
  replicas: {{ .Values.report.database.replicas }}
  selector:
    matchLabels:
      component: {{ .Values.report.database.component }}
  template:
    metadata:
      labels:
        component: {{ .Values.report.database.component }}
    spec:
      volumes:
        - name: report-storage
          persistentVolumeClaim:
            claimName: {{ .Values.report.database.persistentVolumeClaim.name }}
      containers:
        - name: report-database
          image: "{{ .Values.report.database.docker.image.name }}:{{ .Values.report.database.docker.image.tag }}"
          ports:
            - containerPort: {{ .Values.report.database.docker.container.port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: report-storage
              subPath: report-database
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: reports-db
            - name: POSTGRES_PORT
              value: "{{ .Values.report.database.docker.container.port }}"